
import express from "express";
import axios from "axios";
import dotenv from "dotenv";
import OpenAI from "openai";

dotenv.config();

const app = express();
app.use(express.json());

// const openai = new OpenAI({
//   apiKey: process.env.OPENAI_API_KEY,
// });

const openai = new OpenAI({
  apiKey: process.env.GROQ_API_KEY,
  baseURL: "https://api.groq.com/openai/v1"
});

const jiraAuth = {
  username: process.env.JIRA_EMAIL,
  password: process.env.JIRA_API_TOKEN,
};

const jiraApi = axios.create({
  baseURL: process.env.JIRA_BASE_URL,
  auth: jiraAuth,
  headers: {
    "Accept": "application/json",
    "Content-Type": "application/json",
  },
});

async function searchSimilarIssues(query, project) {
  const jql = `project=${project} AND text ~ "${query}" ORDER BY created DESC`;
  const response = await jiraApi.post("/rest/api/3/search", {
    jql,
    maxResults: 3,
  });
  return response.data.issues;
}

async function addComment(issueKey, comment) {
  await jiraApi.post(`/rest/api/3/issue/${issueKey}/comment`, {
    body: comment,
  });
}

async function analyzeTicket(summary, description) {
  const prompt = `
You are a support assistant.
Analyze this Jira ticket and suggest possible investigation direction.

Title: ${summary}
Description: ${description}

Return a short analysis.
`;

  // const completion = await openai.chat.completions.create({
  //   model: "gpt-4o-mini",
  //   messages: [{ role: "user", content: prompt }],
  // });

    const completion = await openai.chat.completions.create({
    model: "llama-3.1-8b-instant",
    messages: [{ role: "user", content: prompt }],
  });

  return completion.choices[0].message.content;
}

app.post("/jira-webhook", async (req, res) => {
  try {
    const issue = req.body.issue;

    const issueKey = issue.key;
    const summary = issue.fields.summary;
    const description =
      issue.fields.description?.content?.[0]?.content?.[0]?.text || "";

    console.log("New Ticket:", issueKey);

    const analysis = await analyzeTicket(summary, description);

    const similarIssues = await searchSimilarIssues(
      summary,
      issue.fields.project.key
    );

    let similarText = "No similar issues found.";
    if (similarIssues.length > 0) {
      similarText = similarIssues
        .map((i) => `• ${i.key} - ${i.fields.summary}`)
        .join("\n");
    }

    const finalComment = `
🤖 AI Investigation Summary:

${analysis}

🔍 Similar Issues:
${similarText}

-- Generated by AI POC
`;

    await addComment(issueKey, finalComment);

    console.log("Comment added successfully.");
    res.status(200).send("Processed");
  } catch (error) {
    console.error("Error:", error.response?.data || error.message);
    res.status(500).send("Error processing ticket");
  }
});

app.listen(process.env.PORT, () => {
  console.log(`Server running on port ${process.env.PORT}`);
});
